version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./nginx-certbot.env
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:
