name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/ghcr.io/coursewarefactory/${{ github.event.repository.name }}/backend
          tags: |
            type=sha
            type=raw,enable=${{ github.ref == format('refs/heads/{0}', 'main') }},value=latest
            type=raw,value=${{ github.ref_name }}-latest
            type=raw,value=${{ github.ref_name }}-{{sha}}
            type=semver,pattern={{version}}
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
